# Docker file to set-up Greyscale's Kibana development environment

FROM ubuntu:20.04

WORKDIR /kibana

# Install nvm
CMD curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash &&
    nvm install &&
    nvm use
