#
# Usage: -  see Dockerfile-gs.dev
#

version: "3.8"

services:
  kibana:
    image: gs-kibana
    volumes:
      # When kibana source is inside code folder on host -- normal dev operation
      - type: bind
        source: ./
        target: /gs-kibana
      # When kibana source is to be copied out from an image using docker cp
        # - type: volume
        #   source: gs-kibana-src
        #   target: /gs-kibana-src
    ports: 
      - "5601:5601" # Kibana
      - "9200:9200" # Elastic Search
      - "9229:9229" # Chrome’s developer tools
      - "9230:9230" # Chrome’s developer tools
      - "9231:9231" # Chrome’s developer tools
  
# When kibana source is to be copied out from an image using docker cp
  # volumes: 
  #   gs-kibana-src: